[font]
size = 15.0

[font.normal] 
style = "Regular"
family = "Source Code Pro"

[font.bold]
style = "Bold"
family = "Source Code Pro"

[font.italic]
style = "Italic"
family = "Source Code Pro"

[font.bold_italic]
style = "Black Italic"
family = "Source Code Pro"

[scrolling]
history = 10000

[colors.primary]
background = '#002b36'
foreground = '#839496'

[colors.normal]
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'

[colors.bright]
black   = '#002b36'
red     = '#cb4b16'
green   = '#586e75'
yellow  = '#657b83'
blue    = '#839496'
magenta = '#6c71c4'
cyan    = '#93a1a1'
white   = '#fdf6e3'
