#!/bin/sh

# An initial copy is needed in $ROOT_DIR/source.

: ${ROOT_DIR:=/srv/backup}
SOURCE_DIR="$ROOT_DIR/source"
BACKUP_DIR="$ROOT_DIR/backup/$(date '+%Y%m%d-%H%M%S')"
BACKUP_LNK="$ROOT_DIR/backup/current"

mkdir -p "$BACKUP_DIR"

if [ ! -h "$BACKUP_LNK" ];then
    rsync -av --delete "$SOURCE_DIR/" "$BACKUP_DIR/"
else
    rsync -av  --delete --link-dest="$BACKUP_LNK/" "$SOURCE_DIR/"  "$BACKUP_DIR/"
fi

ln -f -s "$BACKUP_DIR" "$BACKUP_LNK"
