#!/bin/sh

set -ef

rootpath=$(dirname $(readlink -fm $0))
dotfiles=(aliases bash_profile bashrc gitconfig pythonrc.py tclshrc tmux.conf vimrc)

for f in ${dotfiles[*]};do
    cp -v -f $rootpath/$f $HOME/.$f
done
