LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule systemd_module modules/mod_systemd.so
loadModule unixd_module modules/mod_unixd.so
LoadModule actions_module modules/mod_actions.so
LoadModule alias_module modules/mod_alias.so
LoadModule auth_basic_module modules/mod_auth_basic.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authn_file_module modules/mod_authn_file.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule authz_user_module modules/mod_authz_user.so
LoadModule cgi_module modules/mod_cgi.so
LoadModule deflate_module modules/mod_deflate.so
LoadModule dir_module modules/mod_dir.so
LoadModule env_module modules/mod_env.so
LoadModule expires_module modules/mod_expires.so
LoadModule filter_module modules/mod_filter.so
LoadModule headers_module modules/mod_headers.so
LoadModule include_module modules/mod_include.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule mime_module modules/mod_mime.so
LoadModule negotiation_module modules/mod_negotiation.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_connect_module modules/mod_proxy_connect.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so
LoadModule reqtimeout_module modules/mod_reqtimeout.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule setenvif_module modules/mod_setenvif.so
LoadModule status_module modules/mod_status.so
LoadModule suexec_module modules/mod_suexec.so
LoadModule unique_id_module modules/mod_unique_id.so
LoadModule autoindex_module modules/mod_autoindex.so
LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
LoadModule ssl_module modules/mod_ssl.so

User apache
Group apache
Listen 80
Listen 443 https
ServerRoot /etc/httpd
ServerName {{ httpd_servername }}
ServerAdmin no-reply@{{ httpd_servername }}
UseCanonicalName On
ServerSignature Off
ServerTokens ProductOnly
TraceEnable Off
PidFile run/httpd.pid
ErrorLog logs/error_log

SSLProtocol All -SSLv3 -TLSv1 -TLSv1.1
SSLSessionCache shmcb:/run/httpd/sslcache(512000)
SSLSessionCacheTimeout 300
SSLCertificateKeyFile /var/lib/acme/server.key
SSLCertificateFile /var/lib/acme/server.crt

LogLevel warn
LogFormat "%h %l %u %t \"%r\" %>s %b" common
ErrorLog "logs/error_log"
CustomLog "logs/access_log" common

KeepAlive Off
MaxKeepAliveRequests 100
KeepAliveTimeout 15
TimeOut 600
EnableSendfile On

TypesConfig /etc/mime.types
AddDefaultCharset UTF-8
AddType application/x-compress .Z
AddType application/x-gzip .gz .tgz
Addtype image/x-icon .ico
AddType application/x-tar .tgz
AddType text/html .shtml
AddOutputFilter INCLUDES .shtml

DirectoryIndex index.html
DirectoryIndex index.shtml

<Directory />
    AllowOverride none
    Require all denied
</Directory>

<Files ".ht*">
    Require all denied
</Files>

Alias /.well-known/acme-challenge /var/www/challenge
<Directory /var/www/challenge>
    Require all granted
</Directory>

<VirtualHost *:80>
    ServerName {{ httpd_servername }}
    ServerAlias {{ httpd_serveralias }}
    DocumentRoot /var/www/html
    <Directory /var/www/html>
        Options SymlinksIfOwnerMatch IncludesNoExec
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:443>
    ServerName {{ httpd_servername }}
    ServerAlias {{ httpd_serveralias }}
    DocumentRoot /var/www/html
    SSLEngine on
    <Directory /var/www/html>
        Options SymlinksIfOwnerMatch IncludesNoExec
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>
